inputs:
    language-name:
        description: "Language name"
        required: true
        type: choice
        options:
            - java
            - node
            - python
            - go
            - C#
    run-full-matrix:
        description: "Run the full matrix"
        required: false
        type: boolean
        default: "false"

outputs:
    engine-matrix-output:
        description: "Engine matrix"
        value: ${{ steps.load-engine-matrix.outputs.engine-matrix }}
    host-matrix-output:
        description: "Host matrix"
        value: ${{ steps.load-host-matrix.outputs.host-matrix }}
    version-matrix-output:
        description: "Version matrix"
        value: ${{ steps.create-lang-version-matrix.outputs.version-matrix }}

runs:
    using: "composite"
    steps:
        - name: Load engine matrix
          id: load-engine-matrix
          shell: bash
          run: |
              echo 'Select server engines to run tests against'
              if [[ "${{ github.event_name }}" == "pull_request" || "${{ github.event_name }}" == "push" || "${{ inputs.dispatch-run-full-matrix }}" == "false" ]]; then
                  echo 'Pick engines marked as `"run": "always"` only - on PR, push or manually triggered job which does not require full matrix'
                  echo engine-matrix=$(jq -c '[.[] | select(.run == "always")]' < .github/json_matrices/engine-matrix.json) >> $GITHUB_OUTPUT
              else
                  echo 'Pick all engines - on cron (schedule) or if manually triggered job requires a full matrix'
                  echo engine-matrix=$(jq -c . < .github/json_matrices/engine-matrix.json) >> $GITHUB_OUTPUT
              fi
              cat $GITHUB_OUTPUT

        - name: Load host matrix
          id: load-host-matrix
          shell: bash
          run: |
              echo 'Select runners (VMs) to run tests on'
              if [[ "${{ github.event_name }}" == "pull_request" || "${{ github.event_name }}" == "push" || "${{ inputs.dispatch-run-full-matrix }}" == "false" ]]; then
                  echo 'Pick runners marked as '"run": "always"' only - on PR, push or manually triggered job which does not require full matrix'
                  echo host-matrix=$(jq -c '[.[] | select(.run == "always")]' < .github/json_matrices/build-matrix.json) >> $GITHUB_OUTPUT
              else
                  echo 'Pick all runners assigned for the chosen client (language) - on cron (schedule) or if manually triggered job requires a full matrix'
                  echo host-matrix=$(jq -c '[.[] | select(.languages | type == "array" and contains(["${{ inputs.language-name }}"]))]' < .github/json_matrices/build-matrix.json) >> $GITHUB_OUTPUT
              fi
              cat $GITHUB_OUTPUT

        - name: Create language version matrix
          id: create-lang-version-matrix
          shell: bash
          run: |
              echo 'Select language (framework/SDK) versions to run tests on'
              if [[ "${{ github.event_name }}" == "pull_request" || "${{ github.event_name }}" == "push" || "${{ inputs.dispatch-run-full-matrix }}" == "false" ]]; then
                  echo 'Pick language versions listed in 'always-run-versions' only - on PR, push or manually triggered job which does not require full matrix'
                  echo version-matrix=$(jq -c '[.[] | select(.language == "${{ inputs.language-name }}") | .["always-run-versions"] | map({version: .})]' < .github/json_matrices/supported-language-versions.json) >> $GITHUB_OUTPUT
              else
                  echo 'Pick language versions listed in 'versions' - on cron (schedule) or if manually triggered job requires a full matrix'
                  echo version-matrix=$(jq -c '[.[] | select(.language == "${{ inputs.language-name }}") | .versions | map({version: .})]' < .github/json_matrices/supported-language-versions.json) >> $GITHUB_OUTPUT
              fi
              cat $GITHUB_OUTPUT
