name: Rust tests

on:
    push:
        branches: [main]
        paths:
            - logger_core/**
            - glide-core/**
            - submodules/**
            - utils/cluster_manager.py
            - .github/workflows/rust.yml
            - .github/workflows/install-shared-dependencies/action.yml
            - .github/workflows/install-valkey/action.yml
            - .github/json_matrices/build-matrix.json
    pull_request:
        paths:
            - logger_core/**
            - glide-core/**
            - submodules/**
            - utils/cluster_manager.py
            - .github/workflows/rust.yml
            - .github/workflows/install-shared-dependencies/action.yml
            - .github/workflows/install-valkey/action.yml
            - .github/json_matrices/build-matrix.json
    workflow_dispatch:
    workflow_call:
        inputs:
            full-matrix:
                required: true
                type: boolean

concurrency:
    group: rust-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

env:
    CARGO_TERM_COLOR: always

jobs:
    load-engine-matrix:
      runs-on: ubuntu-latest
      outputs:
        matrix: ${{ steps.load-engine-matrix.outputs.matrix }}
      steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Load the engine matrix
            id: load-engine-matrix
            shell: bash
            run: echo "matrix=$(jq -c . < .github/json_matrices/engine-matrix.json)" >> $GITHUB_OUTPUT

    build:
        runs-on: ubuntu-latest
        needs: load-engine-matrix
        timeout-minutes: 15
        strategy:
            fail-fast: false
            matrix:
                engine: ${{ fromJson(needs.load-engine-matrix.outputs.matrix) }}

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
